### ISSUE TITLE
No longer tracks any seren drops

### ISSUE THREAD

**Issue by Meryl** [ZeroGwafa/SerenTracker#4]
Hello there! This app has been my go to for a while now, but since a few weeks this has stopped being able to track drops for me. I am using Alt1 1.6.0 and other things (like AfkWarden, Meg Answers and the Clue Solver) are working normally. Did something change about the messages to Seren Spirits? I'm afraid I don't pay close enough attention to them to know for sure.

If you need any more information please let me know, I'd love to be able to use this app again.

**EDIT:** Some information I figured may be of use to you: The app does seem to recognize the existence of my chatbox, because the little rectangle appears around it like did before (and the message that it's looking for a chatbox disappears).

**EDIT2:** Nvm, I see #3 already has the fix, I guess you aren't active. Bummer!

**Comment by zpar-ky** [comment]
Try adding `https://zpar-ky.github.io/SerenTracker/` as a new alt1 app. Make sure to export your current data to have just in case.

**Comment by ZeroGwafa** [comment]
fixed by merging in zpar's fix
