### ISSUE TITLE
Unable to Locate Chatbox

### ISSUE THREAD

**Issue by SwaeJay** [ZeroGwafa/SerenTracker#5]
@ZeriGwafa 

Chatbox location does not seem to be properly working, and in the drop-down, I only have 1 choice to select from which is "Chat 0" and, when selecting that or letting it auto-find chat, it shows a smaller teal box above my actual chatbox and items are not tracked. Is there any easy fix for this or am I missing something? 

![Chatbox Locator Position](https://github.com/ZeroGwafa/SerenTracker/assets/167026457/b6d62420-c36d-4397-84d8-28f749a00ebf)

**Comment by ZeroGwafa** [comment]
Can't really troubleshoot with a portion of the screen showing.
